resources:
- repo: self

trigger:
- master

steps:
- script: docker login -u $(gpr_user) -p $(gpr_pat) docker.pkg.github.com
  displayName: Logging into GitHub Package Registry
  
- script: docker build -t docker.pkg.github.com/stiviik/altv/stable:$(Build.BuildNumber) -f ./stable/Dockerfile .
  displayName: Building stable docker image
  
- script: docker tag docker.pkg.github.com/stiviik/altv/stable:$(Build.BuildNumber) docker.pkg.github.com/stiviik/altv/stable:latest
  displayName: Create latest stable tag

- script: docker build -t docker.pkg.github.com/stiviik/altv/beta:$(Build.BuildNumber) -f ./beta/Dockerfile .
  displayName: Building beta docker image
 
- script: docker tag docker.pkg.github.com/stiviik/altv/beta:$(Build.BuildNumber) docker.pkg.github.com/stiviik/altv/beta:latest
  displayName: Create latest beta tag

- script: docker push docker.pkg.github.com/stiviik/altv/stable:$(Build.BuildNumber)
  displayName: Pushing stable docker image to GitHub Package Repository
 
- script: docker push docker.pkg.github.com/stiviik/altv/stable:latest
  displayName: Pushing stable docker image to GitHub Package Repository

- script: docker push docker.pkg.github.com/stiviik/altv/beta:$(Build.BuildNumber)
  displayName: Pushing beta docker image to GitHub Package Repository

- script: docker push docker.pkg.github.com/stiviik/altv/beta:latest
  displayName: Pushing beta docker image to GitHub Package Repository
